-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 14:54:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alianza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alianza` (
  `idAlianza` INT NOT NULL,
  `Con quien` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Integrante/s organizacion que mantiene contacto` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlianza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Integrantes de la organización`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Integrantes de la organización` (
  `idIntegrantes de la organización` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `RUT` INT NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Rol` VARCHAR(45) NULL,
  `Alianza_idAlianza` INT NOT NULL,
  PRIMARY KEY (`idIntegrantes de la organización`, `Alianza_idAlianza`),
  INDEX `fk_Integrantes de la organización_Alianza1_idx` (`Alianza_idAlianza` ASC) VISIBLE,
  CONSTRAINT `fk_Integrantes de la organización_Alianza1`
    FOREIGN KEY (`Alianza_idAlianza`)
    REFERENCES `mydb`.`Alianza` (`idAlianza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `RUT` INT NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT NOT NULL,
  `Persona a cargo` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Fecha inicio` DATE NULL,
  `Fecha termino` DATE NULL,
  `Cliente` VARCHAR(45) NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Integrantes de la organización_idIntegrantes de la organización` INT NOT NULL,
  PRIMARY KEY (`idProyectos`, `Clientes_idClientes`, `Integrantes de la organización_idIntegrantes de la organización`),
  INDEX `fk_Proyectos_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Proyectos_Integrantes de la organización1_idx` (`Integrantes de la organización_idIntegrantes de la organización` ASC) VISIBLE,
  CONSTRAINT `fk_Proyectos_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyectos_Integrantes de la organización1`
    FOREIGN KEY (`Integrantes de la organización_idIntegrantes de la organización`)
    REFERENCES `mydb`.`Integrantes de la organización` (`idIntegrantes de la organización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `idEventos` INT NOT NULL,
  `Persona a cargo` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Fecha inicio` DATE NULL,
  `Fecha termino` DATE NULL,
  `Integrantes de la organización_idIntegrantes de la organización` INT NOT NULL,
  PRIMARY KEY (`idEventos`, `Integrantes de la organización_idIntegrantes de la organización`),
  INDEX `fk_Eventos_Integrantes de la organización1_idx` (`Integrantes de la organización_idIntegrantes de la organización` ASC) VISIBLE,
  CONSTRAINT `fk_Eventos_Integrantes de la organización1`
    FOREIGN KEY (`Integrantes de la organización_idIntegrantes de la organización`)
    REFERENCES `mydb`.`Integrantes de la organización` (`idIntegrantes de la organización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
